import type { PresentationManifest } from '../contracts'

/** Procedural presentation vocabulary. Audio entries are cue identifiers, not asset paths. */
export const PRESENTATION_MANIFEST: PresentationManifest = {
  screens: [
    'title',
    'player-creation',
    'school-selection',
    'career-hub',
    'schedule',
    'training',
    'academics',
    'relationships',
    'scouting',
    'game',
    'game-result',
    'draft',
  ],
  cameraCues: [
    'stadium-establishing',
    'pitcher-set',
    'pitch-release',
    'batter-ready',
    'contact-impact',
    'ball-follow',
    'infield-play',
    'outfield-chase',
    'base-runner',
    'plate-play',
    'dugout-reaction',
    'scoreboard-result',
  ],
  animationStates: [
    'idle',
    'ready',
    'windup',
    'pitch',
    'swing',
    'contact',
    'run',
    'field',
    'throw',
    'catch',
    'slide',
    'celebrate',
  ],
  audioCues: [
    'ui-focus',
    'ui-confirm',
    'ui-cancel',
    'crowd-bed',
    'crowd-rise',
    'crowd-cheer',
    'crowd-groan',
    'pitch-windup',
    'ball-release',
    'ball-glove',
    'bat-contact',
    'bat-foul',
    'base-step',
    'runner-slide',
    'umpire-strike',
    'umpire-safe',
    'umpire-out',
    'score-stinger',
  ],
  difficulties: ['rookie', 'prospect', 'legend'],
}
